# Generated by Django 5.2.13 on 2026-04-12 14:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('closed', 'Closed')], max_length=32)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_cases', to='chat.userchat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_cases', to='chat.chatmessage')),
                ('opened_by_admin_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='opened_moderation_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_case',
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='NeuralModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_tag', models.CharField(max_length=64, unique=True)),
                ('model_name', models.CharField(max_length=120)),
                ('provider', models.CharField(max_length=120)),
                ('safety_profile', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_admin_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_model_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'neural_model_version',
                'ordering': ('-deployed_at', 'version_tag'),
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('faq', 'FAQ'), ('announcement', 'Announcement'), ('help_page', 'Help page'), ('legal', 'Legal')], max_length=64)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by_admin_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='updated_site_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site_content',
                'ordering': ('content_type', 'slug'),
            },
        ),
    ]
