# Generated by Django 5.2.13 on 2026-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelaccount",
            name="bot_message_log",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
