# Generated by Django 5.2.13 on 2026-04-12 14:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('response_format', models.CharField(choices=[('scale', 'Scale'), ('text', 'Text'), ('number', 'Number')], max_length=32)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('order_index', models.IntegerField()),
            ],
            options={
                'db_table': 'assessment_question',
                'ordering': ('order_index',),
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=32)),
                ('total_score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('severity_level', models.CharField(blank=True, max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessment_session',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'assessment_template',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('answer_text', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='answers', to='assessments.assessmentquestion')),
            ],
            options={
                'db_table': 'assessment_answer',
            },
        ),
    ]
