# Generated by Django 5.2.13 on 2026-04-12 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_sessions', to='chat.userchat'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.assessmentsession'),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='assessments.assessmenttemplate'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessmenttemplate'),
        ),
        migrations.AddConstraint(
            model_name='assessmentanswer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='uq_session_question'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('template', 'order_index'), name='uq_template_question_order'),
        ),
    ]
