# Generated by Django 5.2.13 on 2026-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crisisevent",
            name="screening_answers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="crisisevent",
            name="screening_question_index",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crisisevent",
            name="screening_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not required"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                ],
                default="not_required",
                max_length=24,
            ),
        ),
    ]
